/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hyejin_TAGON_MainActivity */

#ifndef _Included_com_hyejin_TAGON_MainActivity
#define _Included_com_hyejin_TAGON_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_hyejin_TAGON_MainActivity_PERMISSIONS_REQUEST_CODE
#define com_hyejin_TAGON_MainActivity_PERMISSIONS_REQUEST_CODE 1000L
/*
 * Class:     com_hyejin_TAGON_MainActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
//JNIEXPORT void JNICALL Java_com_hyejin_TAGON_MainActivity_Imageprocessing
//JNIEXPORT void JNICALL Java_com_hyejin_TAGON_ExtractTextFromAlbum_Imageprocessing
JNIEXPORT void JNICALL Java_com_hyejin_TAGON_ExtractTextFromCamera_Imageprocessing
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
